### PR TITLE
Trimed trailing slash off site URLs.

### PR DESCRIPTION
**Pull request by jaydensmith**

### CODE REVIEW

**Review by engram-design — COMMENTED** [review]
What's the idea with this? We're fetching the baseUrl as defined by the site, so shouldn't that be used, regardless of whether it has a trailing slash or not?

**Comment by jaydensmith** [comment]
@engram-design I'm not sure on the reason, but it will always [have a trailing slash](https://github.com/craftcms/cms/blob/develop/src/models/Site.php#L104-L111).

**Comment by engram-design** [comment]
@jaydensmith What I mean is - what's the reason for _not_ having a trailing slash? I feel like the site's URL should behave consistently with what happens if you called `currentSite.baseUrl` in your templates

**Comment by jaydensmith** [comment]
@engram-design functionally there's nothing wrong with it, they are just the only URLs in the navigation that have a trailing slash.

**Pull request merged**
